// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PlayMsgWndCharSeMZ","status":true,"description":"[Ver1.1.0]Play SE for Each Letter on Message Window","parameters":{"default SE":"1","battle default SE":"0","interval":"2","name1":"Cursor1","volume1":"10","pitch1":"150","name2":"Cursor2","volume2":"90","pitch2":"125","name3":"","volume3":"90","pitch3":"100","name4":"","volume4":"90","pitch4":"100","name5":"","volume5":"90","pitch5":"100","advanced":"","prefix":"SE"}},
{"name":"wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}},
{"name":"Yami_8DirEx","status":true,"description":"Player can 8-dir move, also touch input movement.","parameters":{"dir4 Switch ID":"100"}}
];
